"""PI personality constants, meta-archetype mappings, and scoring matrix.

Reference: docs/plans/2026-03-07-pi-personality-role-architecture.md
"""

VALID_PI_PROFILES = (
    "analyzer",
    "strategist",
    "specialist",
    "venturer",
    "scholar",
    "individualist",
    "captain",
    "persuader",
    "promoter",
    "maverick",
    "collaborator",
    "altruist",
    "adapter",
    "guardian",
    "controller",
    "operator",
    "artisan",
)

VALID_META_ARCHETYPES = ("interpreter", "enforcer", "driver")

PI_TO_META_ARCHETYPE: dict[str, str] = {
    # Interpreters (SENSE) — Discovery-native
    "analyzer": "interpreter",
    "strategist": "interpreter",
    "scholar": "interpreter",
    "specialist": "interpreter",
    "individualist": "interpreter",
    # Drivers (DECIDE) — Build/Ship-native
    "captain": "driver",
    "venturer": "driver",
    "maverick": "driver",
    "persuader": "driver",
    "promoter": "driver",
    "collaborator": "driver",
    "adapter": "driver",
    # Enforcers (VALIDATE) — Review-native
    "guardian": "enforcer",
    "controller": "enforcer",
    "operator": "enforcer",
    "artisan": "enforcer",
    "altruist": "enforcer",
}

META_ARCHETYPE_CHAMBER_AFFINITY: dict[str, list[str]] = {
    "interpreter": ["discover"],
    "driver": ["build", "ship"],
    "enforcer": ["review"],
}

VALID_AGENTIC_ROLES = (
    "truth_keeper",
    "system_architect",
    "momentum_builder",
    "evidence_curator",
    "fast_path_executor",
    "maverick_innovator",
    "verifier",
    "friction_taxonomist",
    "authority_validator",
    "cold_route_guardian",
    "semantic_sheriff",
    "process_facilitator",
    "compliance_analyst",
    "observer",
    "drift_detective",
    "team_orchestrator",
)

# 17 PI profiles × 16 agentic roles scoring matrix (0.0–1.0)
# From design doc Section 3
SCORING_MATRIX: dict[str, dict[str, float]] = {
    "analyzer": {
        "truth_keeper": 0.6,
        "system_architect": 0.5,
        "momentum_builder": 0.2,
        "evidence_curator": 0.9,
        "fast_path_executor": 0.3,
        "maverick_innovator": 0.1,
        "verifier": 0.7,
        "friction_taxonomist": 0.4,
        "authority_validator": 0.5,
        "cold_route_guardian": 0.6,
        "semantic_sheriff": 0.7,
        "process_facilitator": 0.3,
        "compliance_analyst": 0.8,
        "observer": 0.7,
        "drift_detective": 0.8,
        "team_orchestrator": 0.2,
    },
    "strategist": {
        "truth_keeper": 0.7,
        "system_architect": 0.9,
        "momentum_builder": 0.5,
        "evidence_curator": 0.6,
        "fast_path_executor": 0.4,
        "maverick_innovator": 0.6,
        "verifier": 0.5,
        "friction_taxonomist": 0.5,
        "authority_validator": 0.6,
        "cold_route_guardian": 0.5,
        "semantic_sheriff": 0.6,
        "process_facilitator": 0.4,
        "compliance_analyst": 0.5,
        "observer": 0.6,
        "drift_detective": 0.7,
        "team_orchestrator": 0.3,
    },
    "specialist": {
        "truth_keeper": 0.7,
        "system_architect": 0.6,
        "momentum_builder": 0.2,
        "evidence_curator": 0.8,
        "fast_path_executor": 0.2,
        "maverick_innovator": 0.1,
        "verifier": 0.8,
        "friction_taxonomist": 0.4,
        "authority_validator": 0.5,
        "cold_route_guardian": 0.6,
        "semantic_sheriff": 0.8,
        "process_facilitator": 0.3,
        "compliance_analyst": 0.9,
        "observer": 0.7,
        "drift_detective": 0.7,
        "team_orchestrator": 0.1,
    },
    "venturer": {
        "truth_keeper": 0.3,
        "system_architect": 0.5,
        "momentum_builder": 0.9,
        "evidence_curator": 0.3,
        "fast_path_executor": 0.8,
        "maverick_innovator": 0.7,
        "verifier": 0.2,
        "friction_taxonomist": 0.3,
        "authority_validator": 0.4,
        "cold_route_guardian": 0.2,
        "semantic_sheriff": 0.2,
        "process_facilitator": 0.4,
        "compliance_analyst": 0.2,
        "observer": 0.3,
        "drift_detective": 0.3,
        "team_orchestrator": 0.3,
    },
    "scholar": {
        "truth_keeper": 0.8,
        "system_architect": 0.6,
        "momentum_builder": 0.2,
        "evidence_curator": 0.7,
        "fast_path_executor": 0.2,
        "maverick_innovator": 0.3,
        "verifier": 0.6,
        "friction_taxonomist": 0.5,
        "authority_validator": 0.4,
        "cold_route_guardian": 0.5,
        "semantic_sheriff": 0.7,
        "process_facilitator": 0.3,
        "compliance_analyst": 0.6,
        "observer": 0.8,
        "drift_detective": 0.7,
        "team_orchestrator": 0.2,
    },
    "individualist": {
        "truth_keeper": 0.7,
        "system_architect": 0.8,
        "momentum_builder": 0.3,
        "evidence_curator": 0.5,
        "fast_path_executor": 0.3,
        "maverick_innovator": 0.8,
        "verifier": 0.5,
        "friction_taxonomist": 0.6,
        "authority_validator": 0.5,
        "cold_route_guardian": 0.5,
        "semantic_sheriff": 0.6,
        "process_facilitator": 0.3,
        "compliance_analyst": 0.4,
        "observer": 0.6,
        "drift_detective": 0.7,
        "team_orchestrator": 0.2,
    },
    "captain": {
        "truth_keeper": 0.5,
        "system_architect": 0.5,
        "momentum_builder": 0.9,
        "evidence_curator": 0.3,
        "fast_path_executor": 0.7,
        "maverick_innovator": 0.5,
        "verifier": 0.3,
        "friction_taxonomist": 0.4,
        "authority_validator": 0.6,
        "cold_route_guardian": 0.3,
        "semantic_sheriff": 0.3,
        "process_facilitator": 0.5,
        "compliance_analyst": 0.3,
        "observer": 0.4,
        "drift_detective": 0.3,
        "team_orchestrator": 0.7,
    },
    "persuader": {
        "truth_keeper": 0.3,
        "system_architect": 0.3,
        "momentum_builder": 0.7,
        "evidence_curator": 0.3,
        "fast_path_executor": 0.9,
        "maverick_innovator": 0.5,
        "verifier": 0.2,
        "friction_taxonomist": 0.5,
        "authority_validator": 0.3,
        "cold_route_guardian": 0.2,
        "semantic_sheriff": 0.2,
        "process_facilitator": 0.6,
        "compliance_analyst": 0.2,
        "observer": 0.3,
        "drift_detective": 0.2,
        "team_orchestrator": 0.5,
    },
    "promoter": {
        "truth_keeper": 0.3,
        "system_architect": 0.2,
        "momentum_builder": 0.7,
        "evidence_curator": 0.2,
        "fast_path_executor": 0.7,
        "maverick_innovator": 0.4,
        "verifier": 0.2,
        "friction_taxonomist": 0.5,
        "authority_validator": 0.2,
        "cold_route_guardian": 0.1,
        "semantic_sheriff": 0.2,
        "process_facilitator": 0.8,
        "compliance_analyst": 0.2,
        "observer": 0.3,
        "drift_detective": 0.2,
        "team_orchestrator": 0.6,
    },
    "maverick": {
        "truth_keeper": 0.3,
        "system_architect": 0.5,
        "momentum_builder": 0.7,
        "evidence_curator": 0.3,
        "fast_path_executor": 0.6,
        "maverick_innovator": 1.0,
        "verifier": 0.2,
        "friction_taxonomist": 0.4,
        "authority_validator": 0.3,
        "cold_route_guardian": 0.2,
        "semantic_sheriff": 0.2,
        "process_facilitator": 0.3,
        "compliance_analyst": 0.2,
        "observer": 0.4,
        "drift_detective": 0.4,
        "team_orchestrator": 0.3,
    },
    "collaborator": {
        "truth_keeper": 0.4,
        "system_architect": 0.4,
        "momentum_builder": 0.6,
        "evidence_curator": 0.4,
        "fast_path_executor": 0.5,
        "maverick_innovator": 0.4,
        "verifier": 0.4,
        "friction_taxonomist": 0.6,
        "authority_validator": 0.3,
        "cold_route_guardian": 0.3,
        "semantic_sheriff": 0.3,
        "process_facilitator": 0.7,
        "compliance_analyst": 0.3,
        "observer": 0.4,
        "drift_detective": 0.3,
        "team_orchestrator": 0.9,
    },
    "altruist": {
        "truth_keeper": 0.5,
        "system_architect": 0.3,
        "momentum_builder": 0.3,
        "evidence_curator": 0.4,
        "fast_path_executor": 0.3,
        "maverick_innovator": 0.2,
        "verifier": 0.4,
        "friction_taxonomist": 0.8,
        "authority_validator": 0.3,
        "cold_route_guardian": 0.4,
        "semantic_sheriff": 0.3,
        "process_facilitator": 0.6,
        "compliance_analyst": 0.4,
        "observer": 0.5,
        "drift_detective": 0.4,
        "team_orchestrator": 0.8,
    },
    "adapter": {
        "truth_keeper": 0.4,
        "system_architect": 0.4,
        "momentum_builder": 0.6,
        "evidence_curator": 0.5,
        "fast_path_executor": 0.6,
        "maverick_innovator": 0.4,
        "verifier": 0.5,
        "friction_taxonomist": 0.5,
        "authority_validator": 0.4,
        "cold_route_guardian": 0.4,
        "semantic_sheriff": 0.4,
        "process_facilitator": 0.7,
        "compliance_analyst": 0.4,
        "observer": 0.5,
        "drift_detective": 0.4,
        "team_orchestrator": 0.5,
    },
    "guardian": {
        "truth_keeper": 0.6,
        "system_architect": 0.4,
        "momentum_builder": 0.2,
        "evidence_curator": 0.5,
        "fast_path_executor": 0.2,
        "maverick_innovator": 0.1,
        "verifier": 0.7,
        "friction_taxonomist": 0.5,
        "authority_validator": 0.7,
        "cold_route_guardian": 1.0,
        "semantic_sheriff": 0.7,
        "process_facilitator": 0.5,
        "compliance_analyst": 0.7,
        "observer": 0.6,
        "drift_detective": 0.6,
        "team_orchestrator": 0.3,
    },
    "controller": {
        "truth_keeper": 0.6,
        "system_architect": 0.6,
        "momentum_builder": 0.3,
        "evidence_curator": 0.5,
        "fast_path_executor": 0.3,
        "maverick_innovator": 0.2,
        "verifier": 0.7,
        "friction_taxonomist": 0.4,
        "authority_validator": 0.9,
        "cold_route_guardian": 0.7,
        "semantic_sheriff": 0.8,
        "process_facilitator": 0.4,
        "compliance_analyst": 0.6,
        "observer": 0.5,
        "drift_detective": 0.6,
        "team_orchestrator": 0.2,
    },
    "operator": {
        "truth_keeper": 0.4,
        "system_architect": 0.4,
        "momentum_builder": 0.4,
        "evidence_curator": 0.4,
        "fast_path_executor": 0.5,
        "maverick_innovator": 0.2,
        "verifier": 0.6,
        "friction_taxonomist": 0.5,
        "authority_validator": 0.5,
        "cold_route_guardian": 0.6,
        "semantic_sheriff": 0.5,
        "process_facilitator": 0.8,
        "compliance_analyst": 0.6,
        "observer": 0.6,
        "drift_detective": 0.5,
        "team_orchestrator": 0.4,
    },
    "artisan": {
        "truth_keeper": 0.5,
        "system_architect": 0.5,
        "momentum_builder": 0.3,
        "evidence_curator": 0.6,
        "fast_path_executor": 0.3,
        "maverick_innovator": 0.3,
        "verifier": 0.8,
        "friction_taxonomist": 0.5,
        "authority_validator": 0.5,
        "cold_route_guardian": 0.6,
        "semantic_sheriff": 0.6,
        "process_facilitator": 0.4,
        "compliance_analyst": 0.7,
        "observer": 0.6,
        "drift_detective": 0.6,
        "team_orchestrator": 0.2,
    },
}


def get_meta_archetype(pi_profile: str) -> str | None:
    """Get the meta-archetype for a PI profile. Returns None if invalid."""
    return PI_TO_META_ARCHETYPE.get(pi_profile)


def get_chamber_affinity(meta_archetype: str) -> list[str]:
    """Get chamber affinity list for a meta-archetype."""
    return META_ARCHETYPE_CHAMBER_AFFINITY.get(meta_archetype, [])


def get_top_agentic_roles(pi_profile: str, n: int = 3) -> list[tuple[str, float]]:
    """Return top N agentic roles for a PI profile, sorted by score descending.

    Returns list of (role_name, score) tuples.
    """
    scores = SCORING_MATRIX.get(pi_profile, {})
    sorted_roles = sorted(scores.items(), key=lambda x: x[1], reverse=True)
    return sorted_roles[:n]
