"""Default UX preference profiles per PI personality type.

Reference: docs/plans/2026-03-07-pi-personality-role-architecture.md, Section 4
"""

import copy

VALID_DENSITY_VALUES = ("minimal", "moderate", "dense")
VALID_STRUCTURE_VALUES = ("hierarchical", "narrative", "visual", "tabular")
VALID_PACE_VALUES = ("deliberate", "moderate", "rapid")

UX_PROFILES: dict[str, dict] = {
    "analyzer": {
        "informationDensity": "dense",
        "structurePreference": "tabular",
        "pacePreference": "deliberate",
        "compensationPatterns": [
            "add_decision_deadlines",
            "show_progress_momentum_indicators",
            "surface_action_recommendations",
            "add_collaboration_prompts",
        ],
        "explanationStyle": "data-first",
        "notificationFrequency": "batch-daily",
        "feedbackPreference": "detailed-written",
        "defaultAutonomyLevel": 2,
        "aiExplanationDepth": "detailed",
        "aiConfirmationStyle": "always-ask",
        "defaultTriptychWeights": [25, 40, 35],
        "preferredPanelFocus": "orchestrate",
    },
    "strategist": {
        "informationDensity": "moderate",
        "structurePreference": "hierarchical",
        "pacePreference": "moderate",
        "compensationPatterns": [
            "add_implementation_checklists",
            "show_team_sentiment_indicators",
            "surface_detail_level_warnings",
            "add_delegation_suggestions",
        ],
        "explanationStyle": "context-first",
        "notificationFrequency": "periodic",
        "feedbackPreference": "visual-summary",
        "defaultAutonomyLevel": 3,
        "aiExplanationDepth": "standard",
        "aiConfirmationStyle": "ask-on-risk",
        "defaultTriptychWeights": [30, 40, 30],
        "preferredPanelFocus": "signal",
    },
    "specialist": {
        "informationDensity": "dense",
        "structurePreference": "hierarchical",
        "pacePreference": "deliberate",
        "compensationPatterns": [
            "add_broader_context_summaries",
            "show_impact_beyond_specialty",
            "surface_cross_team_dependencies",
            "add_flexibility_prompts",
        ],
        "explanationStyle": "data-first",
        "notificationFrequency": "batch-daily",
        "feedbackPreference": "detailed-written",
        "defaultAutonomyLevel": 2,
        "aiExplanationDepth": "detailed",
        "aiConfirmationStyle": "always-ask",
        "defaultTriptychWeights": [20, 50, 30],
        "preferredPanelFocus": "orchestrate",
    },
    "venturer": {
        "informationDensity": "minimal",
        "structurePreference": "visual",
        "pacePreference": "rapid",
        "compensationPatterns": [
            "add_risk_assessment_gates",
            "show_team_impact_warnings",
            "surface_compliance_requirements",
            "add_reflection_checkpoints",
        ],
        "explanationStyle": "action-first",
        "notificationFrequency": "real-time",
        "feedbackPreference": "quick-status",
        "defaultAutonomyLevel": 4,
        "aiExplanationDepth": "brief",
        "aiConfirmationStyle": "notify-only",
        "defaultTriptychWeights": [20, 55, 25],
        "preferredPanelFocus": "orchestrate",
    },
    "scholar": {
        "informationDensity": "dense",
        "structurePreference": "hierarchical",
        "pacePreference": "deliberate",
        "compensationPatterns": [
            "add_action_deadline_prompts",
            "show_practical_application_links",
            "surface_team_needs_indicators",
            "add_synthesis_checkpoints",
        ],
        "explanationStyle": "data-first",
        "notificationFrequency": "batch-daily",
        "feedbackPreference": "detailed-written",
        "defaultAutonomyLevel": 2,
        "aiExplanationDepth": "detailed",
        "aiConfirmationStyle": "always-ask",
        "defaultTriptychWeights": [30, 40, 30],
        "preferredPanelFocus": "signal",
    },
    "individualist": {
        "informationDensity": "moderate",
        "structurePreference": "hierarchical",
        "pacePreference": "moderate",
        "compensationPatterns": [
            "add_team_alignment_checks",
            "show_consensus_indicators",
            "surface_collaboration_opportunities",
            "add_communication_prompts",
        ],
        "explanationStyle": "context-first",
        "notificationFrequency": "periodic",
        "feedbackPreference": "detailed-written",
        "defaultAutonomyLevel": 3,
        "aiExplanationDepth": "detailed",
        "aiConfirmationStyle": "ask-on-risk",
        "defaultTriptychWeights": [25, 45, 30],
        "preferredPanelFocus": "orchestrate",
    },
    "captain": {
        "informationDensity": "moderate",
        "structurePreference": "visual",
        "pacePreference": "rapid",
        "compensationPatterns": [
            "add_patience_indicators",
            "show_detail_coverage_gaps",
            "surface_quiet_team_voices",
            "add_process_compliance_checks",
        ],
        "explanationStyle": "action-first",
        "notificationFrequency": "real-time",
        "feedbackPreference": "visual-summary",
        "defaultAutonomyLevel": 4,
        "aiExplanationDepth": "standard",
        "aiConfirmationStyle": "ask-on-risk",
        "defaultTriptychWeights": [30, 40, 30],
        "preferredPanelFocus": "signal",
    },
    "persuader": {
        "informationDensity": "moderate",
        "structurePreference": "narrative",
        "pacePreference": "rapid",
        "compensationPatterns": [
            "add_data_validation_prompts",
            "show_follow_through_tracking",
            "surface_analytical_gaps",
            "add_depth_before_breadth_nudges",
        ],
        "explanationStyle": "action-first",
        "notificationFrequency": "real-time",
        "feedbackPreference": "quick-status",
        "defaultAutonomyLevel": 4,
        "aiExplanationDepth": "brief",
        "aiConfirmationStyle": "notify-only",
        "defaultTriptychWeights": [25, 50, 25],
        "preferredPanelFocus": "orchestrate",
    },
    "promoter": {
        "informationDensity": "minimal",
        "structurePreference": "narrative",
        "pacePreference": "rapid",
        "compensationPatterns": [
            "add_structured_task_lists",
            "show_detail_completion_tracking",
            "surface_analytical_requirements",
            "add_focus_mode_suggestions",
        ],
        "explanationStyle": "action-first",
        "notificationFrequency": "real-time",
        "feedbackPreference": "quick-status",
        "defaultAutonomyLevel": 5,
        "aiExplanationDepth": "brief",
        "aiConfirmationStyle": "notify-only",
        "defaultTriptychWeights": [35, 40, 25],
        "preferredPanelFocus": "signal",
    },
    "maverick": {
        "informationDensity": "moderate",
        "structurePreference": "visual",
        "pacePreference": "rapid",
        "compensationPatterns": [
            "add_consensus_building_tools",
            "show_stakeholder_alignment_status",
            "surface_process_requirements",
            "add_completion_tracking",
        ],
        "explanationStyle": "action-first",
        "notificationFrequency": "real-time",
        "feedbackPreference": "visual-summary",
        "defaultAutonomyLevel": 4,
        "aiExplanationDepth": "brief",
        "aiConfirmationStyle": "ask-on-risk",
        "defaultTriptychWeights": [20, 55, 25],
        "preferredPanelFocus": "orchestrate",
    },
    "collaborator": {
        "informationDensity": "moderate",
        "structurePreference": "narrative",
        "pacePreference": "moderate",
        "compensationPatterns": [
            "add_individual_accountability_markers",
            "show_decision_urgency_timers",
            "surface_when_consensus_delays",
            "add_assertiveness_prompts",
        ],
        "explanationStyle": "context-first",
        "notificationFrequency": "periodic",
        "feedbackPreference": "visual-summary",
        "defaultAutonomyLevel": 3,
        "aiExplanationDepth": "standard",
        "aiConfirmationStyle": "ask-on-risk",
        "defaultTriptychWeights": [30, 35, 35],
        "preferredPanelFocus": "signal",
    },
    "altruist": {
        "informationDensity": "moderate",
        "structurePreference": "narrative",
        "pacePreference": "moderate",
        "compensationPatterns": [
            "add_priority_ranking_tools",
            "show_personal_capacity_warnings",
            "surface_boundary_reminders",
            "add_delegation_suggestions",
        ],
        "explanationStyle": "context-first",
        "notificationFrequency": "periodic",
        "feedbackPreference": "visual-summary",
        "defaultAutonomyLevel": 2,
        "aiExplanationDepth": "standard",
        "aiConfirmationStyle": "always-ask",
        "defaultTriptychWeights": [35, 30, 35],
        "preferredPanelFocus": "control",
    },
    "adapter": {
        "informationDensity": "moderate",
        "structurePreference": "visual",
        "pacePreference": "moderate",
        "compensationPatterns": [
            "add_personal_preference_anchoring",
            "show_consistency_tracking",
            "surface_when_flexibility_is_overextending",
            "add_identity_reinforcement_prompts",
        ],
        "explanationStyle": "context-first",
        "notificationFrequency": "periodic",
        "feedbackPreference": "visual-summary",
        "defaultAutonomyLevel": 3,
        "aiExplanationDepth": "standard",
        "aiConfirmationStyle": "ask-on-risk",
        "defaultTriptychWeights": [30, 40, 30],
        "preferredPanelFocus": "orchestrate",
    },
    "guardian": {
        "informationDensity": "dense",
        "structurePreference": "hierarchical",
        "pacePreference": "deliberate",
        "compensationPatterns": [
            "add_innovation_opportunity_alerts",
            "show_when_flexibility_is_safe",
            "surface_team_morale_indicators",
            "add_speed_vs_quality_tradeoff_tools",
        ],
        "explanationStyle": "data-first",
        "notificationFrequency": "batch-daily",
        "feedbackPreference": "detailed-written",
        "defaultAutonomyLevel": 1,
        "aiExplanationDepth": "detailed",
        "aiConfirmationStyle": "always-ask",
        "defaultTriptychWeights": [25, 35, 40],
        "preferredPanelFocus": "control",
    },
    "controller": {
        "informationDensity": "dense",
        "structurePreference": "hierarchical",
        "pacePreference": "deliberate",
        "compensationPatterns": [
            "add_empathy_context_for_decisions",
            "show_team_sentiment_before_enforcement",
            "surface_flexibility_opportunities",
            "add_delegation_vs_control_prompts",
        ],
        "explanationStyle": "data-first",
        "notificationFrequency": "periodic",
        "feedbackPreference": "detailed-written",
        "defaultAutonomyLevel": 2,
        "aiExplanationDepth": "detailed",
        "aiConfirmationStyle": "always-ask",
        "defaultTriptychWeights": [25, 35, 40],
        "preferredPanelFocus": "control",
    },
    "operator": {
        "informationDensity": "moderate",
        "structurePreference": "tabular",
        "pacePreference": "moderate",
        "compensationPatterns": [
            "add_strategic_context_summaries",
            "show_when_process_changes_needed",
            "surface_ownership_opportunities",
            "add_initiative_suggestion_prompts",
        ],
        "explanationStyle": "data-first",
        "notificationFrequency": "periodic",
        "feedbackPreference": "visual-summary",
        "defaultAutonomyLevel": 3,
        "aiExplanationDepth": "standard",
        "aiConfirmationStyle": "ask-on-risk",
        "defaultTriptychWeights": [25, 45, 30],
        "preferredPanelFocus": "orchestrate",
    },
    "artisan": {
        "informationDensity": "dense",
        "structurePreference": "hierarchical",
        "pacePreference": "deliberate",
        "compensationPatterns": [
            "add_deadline_urgency_indicators",
            "show_good_enough_vs_perfect_tradeoffs",
            "surface_team_pace_awareness",
            "add_scope_limitation_reminders",
        ],
        "explanationStyle": "data-first",
        "notificationFrequency": "batch-daily",
        "feedbackPreference": "detailed-written",
        "defaultAutonomyLevel": 2,
        "aiExplanationDepth": "detailed",
        "aiConfirmationStyle": "always-ask",
        "defaultTriptychWeights": [20, 50, 30],
        "preferredPanelFocus": "orchestrate",
    },
}


def get_ux_preferences(pi_profile: str) -> dict | None:
    """Get default UX preferences for a PI profile. Returns a deep copy, or None if invalid."""
    prefs = UX_PROFILES.get(pi_profile)
    if prefs is None:
        return None
    return copy.deepcopy(prefs)
